Login :
       url : http://192.168.1.50/api/Login/Login
       data :
             mobile : 17740194052
             password : 123456
             captcha : 2usw
             captchaUUID : abae3b68-f7c1-4469-bade-0f6bb25f612b
       header :
               Accept : text/plain
               Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVaWQiOjQwNjcsIlNVaWQiOi0xLCJNb2JpbGUiOiIxNzc0MDE5NDA1MiIsIlJlYWxOYW1lIjoi5byg5LiJIiwiRU5hbWUiOiLkvJhFK - iuouWNleWvueaOpeiwg - ivlSIsIkVJRCI6MjAxMzYxLCJFc2Nyb3dOYW1lIjoiIiwiRXNjcm93TW9iaWxlIjoiIiwiaWF0IjoxNjU4Mzk2NDExLCJuYmYiOjE2NTgzOTY0MTEsImV4cCI6MTY1ODQwNzIxMSwiaXNzIjoiU2VydmVyIiwiYXVkIjoiQ2xpZW50In0.GnHCqJxY4RYGQZnUwds7mxkzsPGxoPK3on_BMNtjuXs
               Content-Type : application/json
               Cookie :  Hm_lvt_5051f16aef626d4043437332e22fa100 = 1658123391, 1658210851, 1658280022, 1658364784;Hm_lpvt_5051f16aef626d4043437332e22fa100 = 1658395740
               X-Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5IiwiZSI6IkduSENxSnhZNFJZR1FablV3ZHM3bXhrenNQR3hvUEszb25fQk1OdGp1WHMiLCJzIjozNCwibCI6NywiayI6IkpwYkdVaU8iLCJpYXQiOjE2NTgzOTY0MTEsIm5iZiI6MTY1ODM5NjQxMSwiZXhwIjoxNjU4NDE0NDExLCJpc3MiOiJTZXJ2ZXIiLCJhdWQiOiJDbGllbnQifQ.jx9ihcJjYzvzaTD5cqzv - CC9VZD1qQfIjUZqSKCIkGU

GetOrderList :
              url : http://192.168.1.50/api/Login/Login
              data :
                    captchaUUID : sss
              header :
                    Accept : text/plain






