采购入库单 :
    secretKey : 123456
    data :
     -
      uniqueCode : weg4w4g
      pwNumber : B5599595
      serialNumberTime : "2022-2-3 15:40:00"
      supplierNameId : 12345
      details :
        -
                uniqueCode : weg4w4g
                pwNumber : B5599595
                psn : 13343545
                quantityReal : 2000
                price : 2.389
                priceTaxi : 2.561
                drugsBase_DrugName : "阿莫西林"
                drugsBase_Specification : "20片/盒"
                drugsBase_Manufacturer : "重庆金鹏纺织卫生用品有限公司"
                approvalNumber : "国药准字Z20063568"



采购退货单 :
    secretKey : 123456
    data:
     -
      uniqueCode : wg5weg
      prNumber : B5599595
      serialNumberTime : "2022-6-6 14:33:34"
      supplierNameId : 12345
      details :
        -
                uniqueCode : wg5weg
                prNumber : B5599595
                psn : 13343545
                rebateCount : 1800
                price: 2.389
                priceTaxi: 2.561
                drugsBase_DrugName : "阿莫西林"
                drugsBase_Specification : "20片/盒"
                drugsBase_Manufacturer : "重庆金鹏纺织卫生用品有限公司"
                approvalNumber : "国药准字Z20063568"

配送出库单 :
    secretKey : 123456
    data:
     -
      uniqueCode : wg6weg
      deliNumber : B5599566
      serialNumberTime : "2022-6-6 14:33:34"
      supplierNameId : 12345
      details :
        -
                uniqueCode : wg6weg
                deliNumber : B5599566
                psn : 13343545
                quantityReal : 1800
                price: 2.489
                priceTaxi: 2.661
                drugsBase_DrugName : "阿莫西林"
                drugsBase_Specification : "20片/盒"
                drugsBase_Manufacturer : "重庆金鹏纺织卫生用品有限公司"
                approvalNumber : "国药准字Z20063568"

零售销售单 :
    secretKey : 123456
    data:
     -
      uniqueCode : wg7weg
      rsoNumber : B5599597
      salesOrganizationNo : 1231232
      serialNumberTime : "2022-6-6 14:33:34"
      supplierNameId : 12345
      details :
        -
                uniqueCode : wg7weg
                rsoNumber : B5599597
                psn : 13343545
                quantity : 1800
                price: 2.489
                priceTaxi: 2.661
                drugsBase_DrugName : "阿莫西林"
                drugsBase_Specification : "20片/盒"
                drugsBase_Manufacturer : "重庆金鹏纺织卫生用品有限公司"
                approvalNumber : "国药准字Z20063568"
